### ISSUE TITLE
Imports failing with fiona/osgeo

### ISSUE THREAD

**Issue by bekozi** [ioos/conda-recipes#771]
``fiona``/``osgeo`` began failing recently (I noticed today). The error can be reproduced using:

``docker run continuumio/anaconda bash -c "conda install -y -c ioos fiona; python -c 'import fiona'"``
    or
``docker run continuumio/anaconda bash -c "conda install -y -c ioos gdal==1.11.3; python -c 'import osgeo'"``

The issue is with a ``libcom_err.so.3`` missing link:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/fiona/__init__.py", line 72, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/opt/conda/lib/python2.7/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libcom_err.so.3: cannot open shared object file: No such file or directory
```

This link is absent in the ``GDAL`` shared library:

```sh
$ ldd libgdal.so
libgdal.so:
	linux-vdso.so.1 =>  (0x00007fff6bf5d000)
	libproj.so.9 => /opt/conda/envs/fiona/lib/././libproj.so.9 (0x00007ffe3e0d1000)
	libgeos_c.so.1 => /opt/conda/envs/fiona/lib/././libgeos_c.so.1 (0x00007ffe3de94000)
	libgeos-3.4.2.so => /opt/conda/envs/fiona/lib/././libgeos-3.4.2.so (0x00007ffe3d93d000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007ffe3d710000)
	libxerces-c-3.1.so => /opt/conda/envs/fiona/lib/././libxerces-c-3.1.so (0x00007ffe3d11d000)
	libopenjp2.so.7 => /opt/conda/envs/fiona/lib/././libopenjp2.so.7 (0x00007ffe3ced1000)
	libnetcdf.so.7 => /opt/conda/envs/fiona/lib/././libnetcdf.so.7 (0x00007ffe39b5e000)
	libhdf5_hl.so.10 => /opt/conda/envs/fiona/lib/././libhdf5_hl.so.10 (0x00007ffe39940000)
	libhdf5.so.10 => /opt/conda/envs/fiona/lib/././libhdf5.so.10 (0x00007ffe39488000)
	libjpeg.so.8 => /opt/conda/envs/fiona/lib/././libjpeg.so.8 (0x00007ffe39251000)
	libpq.so.5 => /opt/conda/envs/fiona/lib/././libpq.so.5 (0x00007ffe39020000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffe38e03000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffe38bff000)
	libcurl.so.4 => /opt/conda/envs/fiona/lib/././libcurl.so.4 (0x00007ffe389a0000)
	libssl.so.1.0.0 => /opt/conda/envs/fiona/lib/././libssl.so.1.0.0 (0x00007ffe38728000)
	libcrypto.so.1.0.0 => /opt/conda/envs/fiona/lib/././libcrypto.so.1.0.0 (0x00007ffe382f3000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007ffe380b3000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007ffe37dde000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007ffe37bb5000)
	libcom_err.so.3 => not found
	libz.so.1 => /opt/conda/envs/fiona/lib/././libz.so.1 (0x00007ffe3799e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ffe37796000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffe3748f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffe3720c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffe36e81000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffe36c6b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffe3f27a000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007ffe36a66000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007ffe3685d000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007ffe36658000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007ffe36442000)
```

I'm guessing something changed in the default channel as there hasn't been a super recent IOOS build of ``GDAL`` or ``fiona``, and they used to work flawlessly. Any idea what this might be? I wanted to check before digging further...

#goodtimeswithgdal2.0

**Comment by ocefpaf** [comment]
Ben,

I am out of office until next week. I'll take a look at that as soon as I
get back. But I have a suspicion that the default channel fiona and gdal
were fixed. If so we'll drop them here.

**Comment by mattexx** [comment]
Here's a simple workaround:

    docker run continuumio/anaconda bash -c "conda install -y -c ioos fiona krb5; python -c 'import fiona'"

Seems that something is missing `krb5` but that's as far as I've dug.

**Comment by bekozi** [comment]
Nice! :+1:

**Comment by darribas** [comment]
Just a note, I've just tried the following on OSX and py2.7:

```
conda create -n test ipython
conda install fiona krb5
```
And it returns the same error as reported above. However, if I ping to `fiona<1.6`:

```
conda create -n test ipython
conda install "fiona<1.6" krb5
```

It seems to work properly.

**Comment by darribas** [comment]
Just checked again, installing `krb5` does not solve the problem in OSX, it does in Linux. Any ideas how to fix it for OSX?

**Comment by ocefpaf** [comment]
@darribas the "fixed" gdal just landed on the channel. Did you try those? They worked on the CI (See https://travis-ci.org/ioos/conda-recipes/builds/113171062, but note that the failure is due to a timeout, I kept re-starting the CI and all the files got build and uploaded.)

Can you also send me the results of the following commands:

```shell
conda list gdal
conda list fiona
python -c 'import osgeo; print(osgeo.__version__)'
python -c 'import fiona; print(fiona.__version__)'

**Comment by darribas** [comment]
@ocefpaf Thanks very much for all the help. Here're the outputs:

```
(pydata_exp)dh073084:envs dani$ conda list gdal
# packages in environment at /Users/dani/anaconda/envs/pydata_exp:
#
gdal                      1.11.3              np110py27_2    ioos
(pydata_exp)dh073084:envs dani$
```

```
(pydata_exp)dh073084:envs dani$ conda list fiona
# packages in environment at /Users/dani/anaconda/envs/pydata_exp:
#
fiona                     1.6.3               np110py27_0    ioos
(pydata_exp)dh073084:envs dani$
```

```
(pydata_exp)dh073084:envs dani$ python -c 'import osgeo; print(osgeo.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dani/anaconda/envs/pydata_exp/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/dani/anaconda/envs/pydata_exp/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: dlopen(/Users/dani/anaconda/envs/pydata_exp/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: /usr/local/lib/libjson-c.2.dylib
  Referenced from: /Users/dani/anaconda/envs/pydata_exp/lib/libgdal.1.dylib
  Reason: image not found
(pydata_exp)dh073084:envs dani$
```

```
(pydata_exp)dh073084:envs dani$ python -c 'import fiona; print(fiona.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/dani/anaconda/envs/pydata_exp/lib/python2.7/site-packages/fiona/__init__.py", line 72, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/Users/dani/anaconda/envs/pydata_exp/lib/python2.7/site-packages/fiona/collection.py", line 7, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/dani/anaconda/envs/pydata_exp/lib/python2.7/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libjson-c.2.dylib
  Referenced from: /Users/dani/anaconda/envs/pydata_exp/lib/libgdal.1.dylib
  Reason: image not found
(pydata_exp)dh073084:envs dani$
```

**Comment by ocefpaf** [comment]
@darribas I don't own a Mac to test this but it seems that `libjson` is not installed in your system. I could create a conda package for it but it seems that `libjson` is something "trivial" to install. (Imagine lots of quotes there as nothing is really trivial when it comes installing libraries :wink:)

I want to avoid bloating the channel with packages that can be easily installed via the system package manager. Can you try to get `libjson` going on your system?  (I know that the OS X image on Travis-CI has it because gdal does work there.)

Please let me know your findings.

**Comment by darribas** [comment]
@ocefpaf Thanks very much, I think I've figured it out based on your message. The thing was that I was only installing `gdal`, and I also should be adding explicitly it seems `libgdal`, which brings `libjson`, etc. Once added, everything seems to run correctly!

**Comment by ocefpaf** [comment]
Can you send me the results of `conda lista gdal` and `conda lista libgdal`?

I don't create the `libgdal`. That is a *default* channel name. (I disagree with the name because that is not a library only package. Libgdal has executables and other bindings. I also disagree on calling the python bindings `gdal`.  The IOOS package is a single exe+libs+bindings package named `gdal`.)

Either way.  I believe the default channel fixed the issue with fiona, so maybe there is no longer a need for the IOOS version of gdal.

**Comment by darribas** [comment]
I assume you mean `conda list` (`lista` gave me an error):

```
(pydata_exp)dh073084:~ dani$ conda list gdal
# packages in environment at /Users/dani/anaconda/envs/pydata_exp:
#
gdal                      1.11.3              np110py27_2    ioos
libgdal                   1.11.2                        2    defaults
(pydata_exp)dh073084:~ dani$
```
```
(pydata_exp)dh073084:~ dani$ conda list libgdal
# packages in environment at /Users/dani/anaconda/envs/pydata_exp:
#
libgdal                   1.11.2                        2
(pydata_exp)dh073084:~ dani$
```

**Comment by ocefpaf** [comment]
> I assume you mean conda list (lista gave me an error):

Oops.

As I suspected you are getting `libgdal` from the default channel. If that is working... good.  I will try to straight things out when moving `gdal` to `conda-forge`.

**Comment by nickeubank** [comment]
Hi all -- this is listed as closed, but doesn't seem to be fixed having issues, at least when building in a development environment:

	conda create --name test_env6 python=3.4   
	source activate test_env6
	conda install -y -c ioos fiona 
	python -c 'import fiona' 

Generates:


	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/Users/Nick/anaconda/envs/test_env6/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
	    from fiona.collection import Collection, BytesCollection, vsi_path
	  File "/Users/Nick/anaconda/envs/test_env6/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
	    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
	ImportError: dlopen(/Users/Nick/anaconda/envs/test_env6/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
	  Referenced from: /Users/Nick/anaconda/envs/test_env6/lib/libgdal.1.dylib
	  Reason: image not found

Is this resolved?

**Comment by pelson** [comment]
Cross linking with https://github.com/conda-forge/fiona-feedstock/issues/1. I think they are one and the same issue @nickeubank, and they all relate to linking against a system library (which we shouldn't be doing). I suspect there is a quick workaround (but by no means a long term solution) by installing the libgif dylib with homebrew. I would have thought https://github.com/conda-forge/fiona-feedstock/issues/1 should be addressable in reasonably short order though, so may be worth waiting for that (or if you know anything about compiling packages, getting your sleeves rolled up on conda-forge?).

Cheers,

**Comment by ocefpaf** [comment]
This is fixed in conda-forge. Anyone following this issue please try to install fiona from there with.

`conda install fiona -c conda-forge`

**Comment by mszell** [comment]
This does not seem to be fixed unfortunately. After running 
`conda install fiona -c conda-forge`
trying to import fiona leads to:
`ImportError: dlopen(/Users/mszell/anaconda/lib/python3.6/site-packages/fiona/ogrext.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/mszell/anaconda/lib/libgdal.20.dylib
  Reason: image not found`

**Comment by ocefpaf** [comment]
Please open an issue in the conda-forge `fiona` feedstock. But read this first: http://conda-forge.github.io/docs/conda-forge_gotchas.html
